name: meu_jardim_app

description: meu jardim é um app para auxiliar na rotina de seus cultivos :)

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_phosphor_icons: ^0.0.1+6
  image_picker: ^0.8.6
  google_fonts: ^4.0.3
  url_launcher: ^6.2.4
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  intl: ^0.19.0
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  uuid: ^4.3.3
  http: ^1.2.1
  flutter_local_notifications: ^17.0.0
  cached_network_image: ^3.3.1
  flutter_speed_dial: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo_dark.png
    - lib/assets/logo_light.png
    - lib/assets/no_plants_dark.png
    - lib/assets/no_plants_light.png
    - lib/assets/sem-gatos.png
    - lib/assets/sem-cachorro.png
    - lib/assets/no-eat.png
    
   
